export const VIDEO_REQUEST = 'VIDEO_REQUEST'
export const VIDEO_SUCCESS = 'VIDEO_SUCCESS'
export const VIDEO_FAIL = 'VIDEO_FAIL'

export const VIDEO_PAGES_REQUEST = 'VIDEO_PAGES_REQUEST'
export const VIDEO_PAGES_SUCCESS = 'VIDEO_PAGES_SUCCESS'
export const VIDEO_PAGES_FAIL = 'VIDEO_PAGES_FAIL'

export const YOUTUBE_VIDEO_REQUEST = 'YOUTUBE_VIDEO_REQUEST'
export const YOUTUBE_VIDEO_SUCCESS = 'YOUTUBE_VIDEO_SUCCESS'
export const YOUTUBE_VIDEO_FAIL = 'YOUTUBE_VIDEO_FAIL'

export const VIDEO_CREATE_REQUEST = 'VIDEO_CREATE_REQUEST'
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS'
export const VIDEO_CREATE_FAIL = 'VIDEO_CREATE_FAIL'

export const YOUTUBE_TO_DB_REQUEST = 'YOUTUBE_TO_DB_REQUEST'
export const YOUTUBE_TO_DB_SUCCESS = 'YOUTUBE_TO_DB_SUCCESS'
export const YOUTUBE_TO_DB_FAIL = 'YOUTUBE_TO_DB_FAIL'
