export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL'
export const UPLOAD_IMAGE_RESET = 'UPLOAD_IMAGE_RESET'

export const CREATE_IMAGE_REQUEST = 'CREATE_IMAGE_REQUEST'
export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS'
export const CREATE_IMAGE_FAIL = 'CREATE_IMAGE_FAIL'
export const CREATE_IMAGE_RESET = 'CREATE_IMAGE_RESET'

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST'
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS'
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL'
export const IMAGE_DELETE_RESET = 'IMAGE_DELETE_RESET'
