export const POSTS_UPDATE_REQUEST = 'POSTS_UPDATE_REQUEST'
export const POSTS_UPDATE_SUCCESS = 'POSTS_UPDATE_SUCCESS'
export const POSTS_UPDATE_RESET = 'POSTS_UPDATE_RESET'
export const POSTS_UPDATE_FAIL = 'POSTS_UPDATE_FAIL'

export const LIST_POSTS_REQUEST = 'LIST_POSTS_REQUEST'
export const LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS'
export const LIST_POSTS_RESET = 'LIST_POSTS_RESET'
export const LIST_POSTS_FAIL = 'LIST_POSTS_FAIL'

export const POSTS_CREATE_REQUEST = 'POSTS_CREATE_REQUEST'
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS'
export const POSTS_CREATE_FAIL = 'POSTS_CREATE_FAIL'
